import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

import Nav from "@/components/navigation/nav";
import Toaster  from "@/components/ui/toaster";

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  subsets : ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Nav/>
          <Toaster/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
